## Entendiendo el concepto de Tensor

<span style="font-size:20px">

**Definición**. Un *tensor* es una lista ordenada de números.

**Ejemplo**. $x=(1,\:0.4,\:5)$ es un tensor de tamaño $3$, porque tiene $3$ componentes a lo largo de una única fila.

Representación general de un vector: $x=(x_1,x_2,...,x_n)$. Fíjate que $x_i$ denota la componente $i$ de $x$.

Se pueden tener tensores cuyos valores estén ordenados en varias filas (**matrices**):

$$A = \begin{bmatrix}2&1&4&\\
0.5&6&2&\\
-5&1.2&90\\
-100&8&90
\end{bmatrix}
\:\:\:\:\:X=\begin{bmatrix}x_{11}&x_{12}&...&x_{1n}\\
x_{21}&x_{22}&...&x_{2n}\\
...&...&...&...\\
x_{m1}&x_{m2}&...&x_{mn} 
\end{bmatrix}$$

$x_{ij}$ es la componente $j$ de la fila número $i$. 

La matriz tiene tamaño $m\times n$ porque tiene $m$ filas de $n$ componentes cada una.

La matriz tiene tamaño $m\times n$ porque tiene $n$ columnas de $m$ componenetes cada una.

**Observación**. Podemos tener tensores de tamaño $p\times m\times n$ formados por $p$ matrices de tamaño $m\times n$.

Decimos que un vector es un tensor de 1 dimensión; una matriz es un tensor de 2 dimensiones y un tensor de tamaño $p\times m\times n$ es de 3 dimensiones.

Podemos tener tensores de tamaño $q\times p\times m\times n$ y así hasta el infinito.

De forma general, un tensor tendrá $k$ dimensiones si necesitamos $k$ números para especificar su tamaño.

In [ ]:
# Importar librería PyTorch
import torch

In [ ]:
# Crear vector de todos los enteros entre 0 y 11
x = torch.arange(0, 12)   # El "end" no se incluye 
x

In [ ]:
# Acceder al número de componentes.
x.numel()

In [ ]:
# Acceder al tamaño del tensor
x.shape

In [ ]:
# Acceder al número de dimensiones del tensor
x.ndim

In [ ]:
# Crear matriz a partir de los valores del tensor
matrix = x.reshape(3, 4)
matrix, matrix.shape

<span style="font-size:20px">

Una matriz de tamaño $m\times n$ tiene exactamente $m\cdot n$ componentes.

Supón que tenemos un vector de $n$ componentes y queremos transformarlo en una matriz de $w$ filas.

Entonces, para que quepan las $n$ componentes en la matriz necesariamente tendrá que haber $n/w$ columnas, porque $w\cdot n/w=n$.

Es decir, supón que tenemos un vector de $n$ componentes:
- Si queremos transformarlo en una matriz de $w$ filas, necesariamente la matriz tendrá $n/w$ columnas.
- Si queremos transformarlo en una matriz de $p$ columnas, necesariamente la matriz tendrá $n/p$ filas.

Si ponemos $-1$, PyTorch calculará automáticamente el número de filas o de columnas que tiene que tener la nueva matriz.

In [ ]:
x

In [ ]:
# Queremos que tenga 3 filas
x.reshape(3, -1)

In [ ]:
# Queremos que tenga 6 columnas 
x.reshape(-1, 6)

In [ ]:
# Queremos obtener una matriz columna
x.reshape(-1, 1)

In [ ]:
# Si ponemos un número que no es múltiplo de 12 obtenemos error
num_filas = 7

try:
    print(x.reshape(num_filas, -1))
except:
    print(f"No se puede hacer el reshape porque {num_filas} no es múltiplo de 12.")

<span style="font-size:20px">

Más funciones para generar tensores y viendo tensores de 3 dimensiones.

In [ ]:
zeros = torch.zeros((3, 2, 4))
zeros, zeros.shape

In [ ]:
unos = torch.ones((3, 2, 2))
unos, unos.shape

In [ ]:
# Números aleatorios tomados de la distribución normal con media=0 y std=1
normal_random = torch.randn(2, 3, 2, 2)
normal_random, normal_random.shape

In [ ]:
# Números enteros aleatorios entre un máximo y un mínimo
int_random = torch.randint(-100, 100, (5, 4))
int_random, int_random.shape

In [ ]:
# Podemos crear un tensor "a mano" pasandole una lista de Python
torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

## Indexing 

In [ ]:
import torch

In [ ]:
# Crear matriz de números enteros aleatorios.
X = torch.randint(-20, 20, (4, 5))
X, X.shape

In [ ]:
# Acceder a la primera y última fila.
primera_fila = X[0]
ultima_fila = X[-1]
primera_fila, ultima_fila

In [ ]:
# NO devuelve tensor de misma dimensión que el original.
X[0], X[0].shape

In [ ]:
tres_primeras_filas = X[0:3]
tres_primeras_filas, tres_primeras_filas.shape

In [ ]:
# Así podemos obtener una matriz fila.
X[0:1], X[0:1].shape

In [ ]:
X

In [ ]:
# ¿Qué devuelve esto?
## No poner nada = empezar desde el principio.
X[:-2]

In [ ]:
# ¿Qué devuelve esto? 
## No poner nada = ir hasta el final.
X[1:]

In [ ]:
# ¿Y esto?
X[:]

<span style="font-size:20px">

- Vale, ya sabemos como acceder a elementos de la primera dimensión de nuestra matriz $X$.
- ¿Cómo accedemos a las columnas?

In [ ]:
X

In [ ]:
# Acceder a una componente concreta de la matriz.
fila = 0
col = 3
X[fila, col]

In [ ]:
X

In [ ]:
ultima_columna = X[:, -1]

# Nos devuelve un tensor con dimensión diferente al original.
ultima_columna, ultima_columna.shape

In [ ]:
# Obtener en misma dimensión al original.
X[:, -1:], X[:, -1:].shape

In [ ]:
X

In [ ]:
# ¿Qué devuelve esto de aquí?
X[1:3, 1:-1]

In [ ]:
# Crear tensor de tres dimensiones de números enteros aleatorios.
Y = torch.randint(-20, 20, (3, 4, 5))
Y, Y.shape

In [ ]:
# ¿Qué obtendremos?
print(Y[0], Y[0].shape)
# ¿Cómo lo obtenemos con misma dimensión que el original?
Y[0:1], Y[0:1].shape

In [ ]:
# ¿Qué obtenemos?
Y[0:2]

In [ ]:
Y

In [ ]:
# ¿Qué obtenemos?
Y[0:1, 0:2]

In [ ]:
Y

In [ ]:
# ¿Qué obtenemos?
Y[:, :, -2:]

In [ ]:
Y

In [ ]:
# ¿Qué obtenemos con esto de aquí?
Y[1:, 0:2, -3:]

- Tienes que practicar y practicar...

## Operaciones con Tensores.

In [ ]:
# Crear dos matrices del mismo tamaño.
X = torch.randint(-10, 10, (2, 3))
Y = torch.randint(-10, 10, (2, 3))
print(X, X.shape)
print("")
print(Y, Y.shape)

In [ ]:
# Sumar componente a componente
X + Y

In [ ]:
# Multiplicar componente a componente
X*Y

In [ ]:
# Dividir componente a componente
X/Y

In [ ]:
# Potenciación componente a componente
X**Y

<span style="font-size:20px">

- También podemos juntar (stackear) tensores para formar otros nuevos.

In [ ]:
X = torch.randint(-10, 10, (2, 3))
Y = torch.randint(-10, 10, (4, 3))
print(X, X.shape)
print("")
print(Y, Y.shape)

In [ ]:
# Stackear verticalmente
torch.vstack([X, Y, X, Y])

In [ ]:
# No podemos stackear horizontalmente pq no tienen mismo número de filas.
try:
    print(torch.hstack([X, Y]))
except:
    print(f"Num filas X: {X.shape[0]}; Num filas Y: {Y.shape[0]}")

In [ ]:
X.shape

In [ ]:
# Hacemos que Y tenga el mismo número de filas que X con reshape
Y = Y.reshape(X.shape[0], -1)
print(Y, Y.shape)
print(X, X.shape)

# Concatenar horizontalmente
torch.hstack([X,Y])

<span style="font-size:20px">

- Podemos comparar tensores

In [ ]:
X = torch.tensor([[1, 2, 3],[5, 6, 7]])
Y = torch.tensor([[4, 2, -10], [2, 6, 7]])
print(X, X.shape)
print("")
print(Y, Y.shape)

In [ ]:
X == Y

In [ ]:
X >= Y

In [ ]:
X < Y

In [ ]:
equal_XY = (X == Y)
equal_XY

In [ ]:
# Sumar todas componentes entre sí
equal_XY.sum()

In [ ]:
# Sumar componentes columna por columna
equal_XY.sum(dim=0)

In [ ]:
# Sumar componentes fila por fila
equal_XY.sum(dim=1)

<span style="font-size:20px">

- Aplicar funciones sobre las componentes de los tensores.

In [ ]:
X = torch.randint(-10, 10, (2, 3))
print(X, X.shape)

In [ ]:
X.exp()

In [ ]:
# El logaritmo neperiano es la inversa de exp
X.exp().log()

In [ ]:
X.sin()

In [ ]:
# Tipo de dato del tensor
X.dtype

In [ ]:
# Por defecto, PyTorch está acostumbrado a manejar float32
X.float().dtype

In [ ]:
X

In [ ]:
# Necesitas cambiar el tipo de dato de X para que funcione...
X.float().mean(dim=1)

In [ ]:
X.float().std(dim=0)

In [ ]:
X.float().var(dim=1)

## Broadcasting

In [1]:
import torch

In [2]:
X = torch.randint(-10, 10, (4, 3)).float()
Y = torch.randint(-20, 5, (5, 2)).float()
print(X, X.shape)
print("")
print(Y, Y.shape)

tensor([[  1.,   8., -10.],
        [ -2.,  -3.,   6.],
        [ -9.,   5.,   3.],
        [ -1.,  -8.,  -5.]]) torch.Size([4, 3])

tensor([[ -4., -12.],
        [ -1.,  -2.],
        [  1., -14.],
        [-11.,  -8.],
        [ -3., -18.]]) torch.Size([5, 2])


In [3]:
try:
    X + Y 
except RuntimeError:
    print("No podemos operar con tensores de diferente tamaño...")

No podemos operar con tensores de diferente tamaño...


<span style="font-size:20px">

- En ciertas condiciones se podrán realizar operaciones entre tensores de diferente tamaño.
- Supón que tenemos los siguientes tensores:
$$A=\begin{bmatrix}1&2&3\\2&4&1\end{bmatrix}\:\:\:\:\:x=(3,2,1)$$
- Queremos sumar $x$ en todas las filas de $A$.
- Reglas de Broadcasting
    - **Regla 1**: si los dos tensores difieren en el número de dimensiones, al tensor de menor número de dimensiones se le añade un uno en la izquierda. En nuestro ejemplo, el vector $x$, pasaría a ser una matriz fila, es decir, pasaría de tener tamaño $3$ a tamaño $1\times 3$
    $$x=(3,2,1)\:\:\to\:\:x=\begin{bmatrix}3&2&1\end{bmatrix}$$

    - **Regla 2**: Tenemos dos tensores con mismo número de dimensiones, pero con diferente tamaño. Si uno de ellos tiene un $1$ en una dimensión, entonces se expande dicho $1$ hasta que se iguale al valor que hay en el otro tensor. Como $x$ tiene tamaño $1\times 3$, lo expandimos para que tenga tamaño $2\times 3$.
    $$x=\begin{bmatrix}3&2&1\end{bmatrix}\:\:\to\:\:x=\begin{bmatrix}3&2&1\\3&2&1\end{bmatrix}$$

    - **Regla 3**: si el tamaño sigue sin coindicir devuelve error. En nuestro ejemplo el tamaño sí conincide y, por tanto, se lleva a cabo la operación.

In [4]:
X, X.shape

(tensor([[  1.,   8., -10.],
         [ -2.,  -3.,   6.],
         [ -9.,   5.,   3.],
         [ -1.,  -8.,  -5.]]),
 torch.Size([4, 3]))

In [5]:
# Calcular media de las columnas
mean_cols = X.mean(dim=0)
mean_cols, mean_cols.shape

(tensor([-2.7500,  0.5000, -1.5000]), torch.Size([3]))

In [6]:
# Primer paso, poner un uno a la izquierda, para que el vector pase a ser una matriz fila.
broad_mean_cols = mean_cols.reshape(1, -1)
broad_mean_cols, broad_mean_cols.shape

(tensor([[-2.7500,  0.5000, -1.5000]]), torch.Size([1, 3]))

In [7]:
# Segundo: hacer que el 1 en la primera dimensión se iguale al 4 de la matriz X
## Stackeamos verticalmente el número de veces de X.shape[0]
broad_mean_cols = torch.vstack([broad_mean_cols, 
                                broad_mean_cols, 
                                broad_mean_cols, 
                                broad_mean_cols])

broad_mean_cols, broad_mean_cols.shape

(tensor([[-2.7500,  0.5000, -1.5000],
         [-2.7500,  0.5000, -1.5000],
         [-2.7500,  0.5000, -1.5000],
         [-2.7500,  0.5000, -1.5000]]),
 torch.Size([4, 3]))

In [8]:
X

tensor([[  1.,   8., -10.],
        [ -2.,  -3.,   6.],
        [ -9.,   5.,   3.],
        [ -1.,  -8.,  -5.]])

In [9]:
# Ahora realizamos la operación sin problema
X - broad_mean_cols

tensor([[ 3.7500,  7.5000, -8.5000],
        [ 0.7500, -3.5000,  7.5000],
        [-6.2500,  4.5000,  4.5000],
        [ 1.7500, -8.5000, -3.5000]])

In [10]:
mean_cols

tensor([-2.7500,  0.5000, -1.5000])

In [11]:
# Todo lo que hicimos ya lo hace PyTorch automáticamente
X - mean_cols

tensor([[ 3.7500,  7.5000, -8.5000],
        [ 0.7500, -3.5000,  7.5000],
        [-6.2500,  4.5000,  4.5000],
        [ 1.7500, -8.5000, -3.5000]])

In [12]:
X, X.shape

(tensor([[  1.,   8., -10.],
         [ -2.,  -3.,   6.],
         [ -9.,   5.,   3.],
         [ -1.,  -8.,  -5.]]),
 torch.Size([4, 3]))

In [13]:
mean_rows = X.mean(dim=1)
mean_rows, mean_rows.shape

(tensor([-0.3333,  0.3333, -0.3333, -4.6667]), torch.Size([4]))

In [14]:
try:
    print(X - mean_rows)
except RuntimeError:
    print("No se pudo realizar el broadcasting.")

No se pudo realizar el broadcasting.


In [15]:
# Lo solucionamos convirtiendo mean_rows en una matriz columna
mean_rows = mean_rows.reshape(-1, 1) 
mean_rows, mean_rows.shape

(tensor([[-0.3333],
         [ 0.3333],
         [-0.3333],
         [-4.6667]]),
 torch.Size([4, 1]))

In [17]:
X, X.shape

(tensor([[  1.,   8., -10.],
         [ -2.,  -3.,   6.],
         [ -9.,   5.,   3.],
         [ -1.,  -8.,  -5.]]),
 torch.Size([4, 3]))

In [18]:
# Por broadcasting eso ocurrirá al realizar la operación.
torch.hstack([mean_rows, mean_rows, mean_rows])

tensor([[-0.3333, -0.3333, -0.3333],
        [ 0.3333,  0.3333,  0.3333],
        [-0.3333, -0.3333, -0.3333],
        [-4.6667, -4.6667, -4.6667]])

In [19]:
X, X.shape

(tensor([[  1.,   8., -10.],
         [ -2.,  -3.,   6.],
         [ -9.,   5.,   3.],
         [ -1.,  -8.,  -5.]]),
 torch.Size([4, 3]))

In [20]:
mean_rows

tensor([[-0.3333],
        [ 0.3333],
        [-0.3333],
        [-4.6667]])

In [21]:
# A cada fila le restamos su media.
X - mean_rows

tensor([[ 1.3333,  8.3333, -9.6667],
        [-2.3333, -3.3333,  5.6667],
        [-8.6667,  5.3333,  3.3333],
        [ 3.6667, -3.3333, -0.3333]])