# Sección 1.1 Introducción a PyTorch

## 1.1.1 Entendiendo qué es un tensor.

<span style="font-size: 20px">

- ¿Qué es un tensor?

- ¿Qué es la dimensión de un tensor?

- ¿Qué es un tensor de orden-$k$?

- ¿Cómo generamos tensores usando PyTorch?

</span>

In [1]:
# Importar torch
import torch

<span style="font-size: 20px">

- Un *tensor* es una lista ordenada de valores numéricos.

- $x=(1, \:0.4, \:5)$ es un tensor cuyos valores numéricos están ordenados a lo largo de una única fila.

- Denotaremos un vector de dimensión $n$ por $x=(x_1,x_2,...,x_n)$ y diremos que $x_j$ es la componente número $j$ del vector $x$

- Podemos tener tensores cuyos valores estén ordenados en varias filas (matrices)
$$X=\begin{bmatrix}x_{11}&x_{12}&...&x_{1n}\\
x_{21}&x_{22}&...&x_{2n}\\
...&...&...&...\\
x_{m1}&x_{m2}&...&x_{mn} 
\end{bmatrix}$$

- $x_{ij}$ es la componente $j$ de la fila número $i$.

- La matriz tiene dimensión $m\times n$, donde $m$ es el número de filas y $n$ es la dimensión de cada fila.

- La matriz tiene dimensión $m\times n$, donde $n$ es el número de columnas y $m$ es la dimensión de cada columna.

- Un vector $x=(x_1,x_2,...,x_n)$ se puede pensar como una matriz de dimensión $1\times n$.

- Incluso podemos tener tensores de dimensión $m\times n\times p$ formados por $m$ matrices de dimensión $n\times p$

- Un vector es un tensor de orden-1; una matriz es un tensor de orden-2; un tensor de dim $m\times n\times p$ es de orden-3

- Podemos tener un tensor de dimensión $m\times n\times p\times q$, es decir, de orden-4.

- De forma general un tensor será de orden-$k$ en función de cuantos números necesitamos para especificar su dimensión.
</span>

In [7]:
# Vector de enteros en el rango de valores especificado
x = torch.arange(0, 12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [8]:
# ¿Cuantas componentes tiene el tensor?
x.numel()

12

In [9]:
# La shape es la dimensión del tensor.
print(f"Dimensión del tensor: {x.shape}")

# La longitud de la dimensión es el orden del tensor.
print(f"Orden del tensor: {len(x.shape)}")

Dimensión del tensor: torch.Size([12])
Orden del tensor: 1


In [10]:
# Cambiar shape del vector sin alterar valores numéricos
X = x.reshape(3, 4)

# Imprimir información 
print(f"La dimensión del tensor es {X.shape}")
print(f"X es un tensor de orden {len(X.shape)}")
print(f"El número de componentes de X es {X.numel()}")
X

La dimensión del tensor es torch.Size([3, 4])
X es un tensor de orden 2
El número de componentes de X es 12


tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [11]:
def info_tensor(tensor):
    print(f"La dimensión del tensor es {tensor.shape}")
    print(f"Es un tensor de orden {len(tensor.shape)}")
    print(f"El número de componentes del tensor es {tensor.numel()}", "\n")
    print(tensor)

<span style="font-size: 20px">

- Especificar los dos números en reshape es redundante.

- Supón que tenemos un vector de dimensión igual a $n$ y queremos hacer reshape para que tenga dimensión $w\times h$

- Si $h$ ya sabemos que número es entonces $w=n/h$ y viceversa, si $w$ ya lo conocemos entonces $h=n/w$.

- Para inferir de manera automática un número del reshape, podemos poner $-1$.

</span>

In [13]:
x.numel()

12

In [12]:
# Si queremos que la matriz tenga 3 filas
x.reshape(3, -1)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [14]:
# Si queremos que la matriz tenga 6 columnas
x.reshape(-1, 6)

tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]])

In [15]:
# Si queremos convertir el vector en una matriz columna
x.reshape(-1, 1)

tensor([[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11]])

In [16]:
# Como 5 no es múltiplo de 12 obtenemos un error.
x.reshape(5, -1)

RuntimeError: shape '[5, -1]' is invalid for input of size 12

In [17]:
# Muchas veces necesitamos iniciar tensores que solo tengan ceros o unos
# Aquí formamos un tensor formado por 2 matrices, las cuales tienen tamaño 3x4
zeros = torch.zeros(2, 3, 4)
info_tensor(zeros)

La dimensión del tensor es torch.Size([2, 3, 4])
Es un tensor de orden 3
El número de componentes del tensor es 24 

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])


In [18]:
# Tensor de orden=4
ones = torch.ones(2, 3, 2, 2)
info_tensor(ones)

La dimensión del tensor es torch.Size([2, 3, 2, 2])
Es un tensor de orden 4
El número de componentes del tensor es 24 

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])


In [25]:
# Tensor de elementos aleatorios tomados de la distribución normal
# Con media = 0 y std = 1
randn_tensor = torch.randn(3, 4)
info_tensor(randn_tensor)

La dimensión del tensor es torch.Size([3, 4])
Es un tensor de orden 2
El número de componentes del tensor es 12 

tensor([[ 0.9083, -0.6855, -1.0235, -1.7231],
        [-1.3310,  1.1677, -0.4742,  0.8136],
        [ 1.3269,  0.8200,  0.1438, -0.9321]])


In [34]:
# Tensor con enteros aleatorios entre -10 y 10 de dimensión 2x3
randint_tensor = torch.randint(-10, 10, (2, 3)).float()
info_tensor(randint_tensor)

La dimensión del tensor es torch.Size([2, 3])
Es un tensor de orden 2
El número de componentes del tensor es 6 

tensor([[-2., -2., -5.],
        [-9.,  9., -5.]])


In [35]:
torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])

## 1.1.2 Indexing and Slicing

<span style="font-size: 20px">

- ¿Cómo accedemos a diferentes componentes de un tensor?

</span>

In [ ]:
X = torch.randint(-10, 10, (3, 4))
X

In [ ]:
X[0]

In [ ]:
X[0, 3]

In [ ]:
X[1:]

In [ ]:
X[1:, 2]

In [ ]:
X[1:, 2:]

In [ ]:
X = torch.arange(0, 100).reshape(5, 2, 10)
X

In [ ]:
# ¿Cómo accedemos a la última matriz del tensor?
X[-1]

In [ ]:
# ¿Qué nos devolverá esto?
X[1:, 0, -2:]

In [ ]:
# ¿Qué nos devolverá esto?
X[1:, :, 4:]

In [ ]:
# ¿Qué obtendremos?
X[3:, :, 0:2]

In [ ]:
# ¿Qué obtendremos?
X[-2, 0, 5:]

## 1.1.3 Operaciones

- En este vídeo aprenderemos a manipular tensores con operaciones matemáticas

In [ ]:
x = torch.arange(12)

In [ ]:
torch.exp(x)

In [ ]:
torch.sqrt(x)

In [ ]:
torch.log(torch.exp(x))

In [ ]:
x.exp().log()

In [ ]:
# Operaciones de realizan elemento a elemento (elementwise)
# Como los tensores tienen la misma shape no da error
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])
x + y, x - y, x * y, x / y, x ** y

In [ ]:
# Concatenación de tensores
X = torch.arange(12, dtype=torch.float32).reshape((3,4))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
print(X, "\n\n", Y)

In [ ]:
# Error porque tienen diferente shape.
X.reshape(-1, 1) + Y

In [ ]:
# dim=0 implica que se añaden a lo largo de las columnas.
torch.cat((X, Y), dim=0)

In [ ]:
# dim=1 implica que se añaden a lo largo de las filas
torch.cat((X, Y), dim=1)

In [ ]:
X = torch.randint(1, 10, (2, 3))
Y = torch.randint(-10, -1, (5, 3))

# No hay error porque el número de columnas de X es igual al de Y
torch.cat((X, Y), dim=0)

In [ ]:
# Hay error porque el número de filas de Y es diferente al de X
torch.cat((X, Y), dim=1)

In [ ]:
X = torch.randint(-10, 10, (5, 3))
Y = torch.randint(-10, 10, (5, 3))

bool_tensor = X == Y
bool_tensor

In [ ]:
# Suma a lo largo de las columnas.
bool_tensor.sum(dim=0)

In [ ]:
# Suma a lo largo de las filas.
bool_tensor.sum(dim=1)

In [ ]:
# Suma todos los elementos entre sí.
bool_tensor.sum()

## 1.1.4 Broadcasting.

- Hemos visto que podemos hacer operaciones con tensores que tengan la misma *shape*.

- En ciertas condiciones podremos realizar operaciones entre tensores aunque tengan diferente shape.

In [ ]:
a = torch.randint(-10, 10, (5, 3), dtype=float)
print(a)
# Podemos aplicar operaciones de tensores con números sueltos
a + 2, a*2, a**2, a - 2

- Supón que una matriz tiene tamaño $m\times n$.

- Si otra matriz tiene tamaño $1\times n$ entonces se podrá realizar broadcasting.

- Si otra matriz tiene tamaño $m\times 1$ entonces se podrá realizar broadcasting.

In [ ]:
b = torch.randint(-10, 10, (1, 3))
b

In [ ]:
a + b

In [ ]:
c = torch.randint(-10, 10, (a.shape[0], 1))
c

In [ ]:
a + c

In [ ]:
a

In [ ]:
# Estandarizamos la matriz a por columnas
a_col_stan = (a - a.mean(dim=0)) / a.std(dim=0)
a_col_stan.mean(dim=0), a_stan.std(dim=0)

In [ ]:
# Estandarizar por filas 
a_row_stan = (a - a.mean(dim=1).reshape(-1, 1)) / a.std(dim=1).reshape(-1, 1)
a_row_stan.mean(dim=1), a_row_stan.std(dim=1)